---
swagger: "2.0"
info:
  description: Profile Router
  version: "0.1"
  title: Profile Router
paths:
  /api/profile/:profileid:
    get:
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: Gets profile by id
          schema:
            $ref: '#/definitions/Model3'
      security:
      - Secured: []
    put:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: false
        schema:
          $ref: '#/definitions/Model0'
        x-examples:
          application/json: |-
            {
                "first_name": "Jason"
            }
      responses:
        "200":
          description: Updates profile information
          schema:
            $ref: '#/definitions/Model1'
      security:
      - Secured: []
  /api/profile/:profileid/stores:
    get:
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: Gets stores from profile
          schema:
            $ref: '#/definitions/Model2'
      security:
      - Secured: []
  /api/profile:
    get:
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: Gets all profiles
          schema:
            $ref: '#/definitions/Model4'
      security:
      - Secured: []
securityDefinitions:
  Secured:
    type: oauth2
    authorizationUrl: https://example.com
    flow: implicit
    scopes: {}
definitions:
  Model0:
    properties:
      first_name:
        type: string
  Array:
    properties:
      id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      location:
        type: string
      avatar_url:
        type: string
      bio:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
  Model1:
    type: array
    items:
      $ref: '#/definitions/Array'
  Model2_Array:
    properties:
      id:
        type: integer
        format: int32
      owner_id:
        type: string
      name:
        type: string
      description:
        type: string
      location:
        type: string
      phone_number:
        type: string
      images:
        type: array
      operating_hours:
        type: string
      created_at:
        type: integer
        format: int32
  Model2:
    type: array
    items:
      $ref: '#/definitions/Model2_Array'
  Model3:
    properties:
      id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      location:
        type: string
      avatar_url:
        type: string
      bio:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
  Model4_Array:
    properties:
      id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      location:
        type: string
      avatar_url:
        type: string
      bio:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
  Model4:
    type: array
    items:
      $ref: '#/definitions/Model4_Array'
