---
swagger: "2.0"
info:
  description: Stores Routes
  version: "0.1"
  title: Stores Routes
paths:
  /api/stores/:storeid:
    get:
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: Get store information
          schema:
            $ref: '#/definitions/Model2'
      security:
      - Secured: []
  /api/stores/:storeid/products:
    get:
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: Get store products
          schema:
            $ref: '#/definitions/Model3'
      security:
      - Secured: []
  /api/store/:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: false
        schema:
          $ref: '#/definitions/Model0'
        x-examples:
          application/json: |-
            {
                "owner_id": "00ulthapbErVUwVJy4x6",
                "name": "A Dang Store",
                "description": "Nothing but sox here",
                "location": "100 Jerry Street, Maine",
                "phone_number": 5035551212,
                "operating_hours": "9am-7pm"
            }
      responses:
        "201":
          description: Create a store
          schema:
            $ref: '#/definitions/Model4'
      security:
      - Secured: []
  /api/store/:storeid:
    put:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: false
        schema:
          $ref: '#/definitions/Model0'
        x-examples:
          application/json: |-
            {
                "name": "A Danger Store"
            }
      responses:
        "200":
          description: Edit a store profile
          schema:
            $ref: '#/definitions/Model5'
      security:
      - Secured: []
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: false
        schema:
          $ref: '#/definitions/Model1'
        x-examples:
          application/json: |-
            {
                "name": "A Danger Store"
            }
      responses:
        "200":
          description: Delete a store
          schema:
            $ref: '#/definitions/Model6'
      security:
      - Secured: []
securityDefinitions:
  Secured:
    type: oauth2
    authorizationUrl: https://example.com
    flow: implicit
    scopes: {}
definitions:
  Model0:
    properties:
      owner_id:
        type: string
      name:
        type: string
      description:
        type: string
      location:
        type: string
      phone_number:
        type: integer
        format: int64
      operating_hours:
        type: string
  Model1:
    properties:
      name:
        type: string
  Model2:
    properties:
      id:
        type: integer
        format: int32
      owner_id:
        type: string
      name:
        type: string
      description:
        type: string
      location:
        type: string
      phone_number:
        type: string
      images:
        type: array
      operating_hours:
        type: string
      created_at:
        type: integer
        format: int32
  Array:
    properties:
      id:
        type: integer
        format: int32
      store_id:
        type: integer
        format: int32
      name:
        type: string
      description:
        type: string
      price:
        type: integer
        format: int32
      stock_quantity:
        type: integer
        format: int32
      images:
        type: array
      created_at:
        type: integer
        format: int32
      published:
        type: boolean
      delivery:
        type: boolean
      pickup:
        type: boolean
  Model3:
    type: array
    items:
      $ref: '#/definitions/Array'
  Model4:
    properties:
      id:
        type: integer
        format: int32
      owner_id:
        type: string
      name:
        type: string
      description:
        type: string
      location:
        type: string
      phone_number:
        type: string
      images:
        type: object
        properties: {}
      operating_hours:
        type: string
      created_at:
        type: object
        properties: {}
  Model5:
    properties:
      id:
        type: integer
        format: int32
      owner_id:
        type: string
      name:
        type: string
      description:
        type: string
      location:
        type: string
      phone_number:
        type: string
      images:
        type: object
        properties: {}
      operating_hours:
        type: string
      created_at:
        type: object
        properties: {}
  Model6:
    properties:
      id:
        type: integer
        format: int32
      owner_id:
        type: string
      name:
        type: string
      description:
        type: string
      location:
        type: string
      phone_number:
        type: string
      images:
        type: object
        properties: {}
      operating_hours:
        type: string
      created_at:
        type: object
        properties: {}
